### ISSUE TITLE
User Story 1: Create a New Family Tree

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Family-Tree#1]
## Value Proposition

**As a** User,
**I want to** create a new family tree by providing the name and some other details (if applicable) of the primary person (the root of the tree) and be able to add children,
**so that** I can start building and visualizing my family's genealogy and history in an organized manner.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-family-tree/assets/128461153/071ef816-5ece-4830-86a6-a8e071dbc121)​

## Acceptance Criteria

- [ ]  Primary person should be displayed from a (in this case) stored data file. (in the future: The user should be presented with a form to enter the primary person's details (e.g., name, date of birth).)
- [ ] Starting from the main person, their descendants should be able to be displayed
- [ ] The primary person's information (name, date of birth, etc.) should be accurately captured and displayed in the family tree.
      ​

## Tasks

- [ ]  Create a new branch
- [ ] Provide/integrate a file with family data.
- [ ] Design the data structure to store family tree data, including relationships between family members.
- [ ] Develop functionality to add the primary person and initiate the family tree creation process. (creating functions to do so)
- [ ] Add a header with title and style it

     
## Complexity

M / L
